// "use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/footer";
import Providers from "./providers";
import TopNavbar from "@/components/ui/navbar";
import { useState, useEffect, Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <Suspense fallback={<div>Loading...</div>}>
          <Providers>
            <TopNavbar />
            <main className="flex min-h-screen flex-col sm:p-24 p-4">
              {children}
            </main>
            {/* <Footer /> */}
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
